apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: debugpod
  labels:
    app: debug
spec:
  containers:
    - name: debugpod
      image: ubuntu:latest
      imagePullPolicy: IfNotPresent
      command: ["sleep"]
      args: ["3600"]
      resources:
        requests:
          memory: "500Mi"
        limits:
          memory: "1Gi"